name: morphgrower
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.*
  - torch=2.0.0
  - numpy=1.21.2
  - scikit-learn=1.2.2
  - scipy=1.12.0
  - pandas=1.3.5
  - pip
  - pip:
      - pyg==2.3.1
      - morphpy==0.7.2